### ISSUE TITLE
Bind Nuke with ios .net6 project 

### ISSUE THREAD

**Issue by roubachof** [roubachof/NukeProxy#6]
To be able to use Nuke with MAUI, we need to copy the Xamarin.Nuke project, and use ios-net6 target.
Then adapt the github actions to compile and publish the package to nuget.

@Cheesebaron do you think you will have time for that? Thanks pal :)

**Comment by Cheesebaron** [comment]
I will find some time to work on this

**Comment by Cheesebaron** [comment]
Was looking into this a bit. Opening up pandoras box.

Currently we are building fat libraries, from the results produced for iphone (arm64) and iphonesimulator (x86_64). However, the latter is not really available anymore, especially when compiling on a M1 machine with latest Xcode. So now the product for iphonesimulator becomes arm64...

Lipo, the tool that produces the fat library now complains that it cannot combine two arm64 libraries, which makes sense.

I think no matter what we need to look into how to switch to xcframework instead of embedding fat libraries to continue this proxy library. I already tried wandering this route before, without a lot of success.

**Comment by Cheesebaron** [comment]
There is some good info here on how to make xcframework work: https://github.com/xamarin/xamarin-macios/issues/10774

**Comment by J-Swift** [comment]
@Cheesebaron / @roubachof Not sure if its helpful here, but I have an example of generating some xcframework bindings I put here: https://gist.github.com/J-Swift/f30b7aa92ac7ca1bee0b5df142d945ae

It has a little bit of a reliance on how my specific project structure is setup, but that shouldn't be too bad. It was verified working at one point in Maui p13 timeframe, but I haven't re-tested since.
